
package acme.entities.enumerados;

public enum TipoCita {

	PRUEBA_DE_RESECABILIDAD, PRUEBA_DE_IMAGEN, PRUEBA_CITOHISTOLOGICA, CIRUGÍA, PALEATIVOS, ONCOLÓGICO, PRUEBA_BIOPSIA, PRUEBA_COLONOSCOPIA, PRUEBA_SANGRADO_HECES

}
